name: clothing_store
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans-Regular.ttf
        - asset: assets/fonts/EncodeSans-Medium.ttf
        - asset: assets/fonts/EncodeSans-SemiBold.ttf
        - asset: assets/fonts/EncodeSans-Bold.ttf
